/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#c19cff',
        'on-surface': '#ffffff',
        'background': '#0e0e0e',
        'on-secondary-container': '#d2d0cf',
        'surface-container-lowest': '#000000',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        'secondary-container': '#474646',
        'on-primary': '#3f0085',
        'outline': '#777575',
        'primary-container': '#b68aff',
        'tertiary': '#9cff93',
        'secondary': '#e5e2e1',
        'surface-container': '#1a1919',
        'on-surface-variant': '#adaaaa',
        'error': '#ff6e84',
        'outline-variant': '#494847',
        'surface-container-low': '#131313',
        'primary-fixed-dim': '#ab78ff',
        'on-background': '#ffffff',
        'primary': '#c19cff',
        'surface-variant': '#262626',
        'on-primary-container': '#300069',
        'surface': '#0e0e0e',
        'primary-dim': '#9146ff',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Fira Code', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
