/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#fdda24',
        'on-surface': '#0f0f0f',
        background: '#ffffff',
        'on-secondary-container': '#0f0f0f',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#f6f6f6',
        'surface-container-highest': '#eeeeee',
        'secondary-container': '#f6f6f6',
        'on-primary': '#ffffff',
        outline: '#575757',
        'primary-container': '#0f0f0f',
        tertiary: '#fdda24',
        secondary: '#212121',
        'surface-container': '#f6f6f6',
        'on-surface-variant': '#575757',
        error: '#b42318',
        'outline-variant': '#e6e6e6',
        'surface-container-low': '#fafafa',
        'primary-fixed-dim': '#2a2a2a',
        'on-background': '#0f0f0f',
        primary: '#0f0f0f',
        'surface-variant': '#f6f6f6',
        'on-primary-container': '#ffffff',
        surface: '#ffffff',
        'primary-dim': '#2a2a2a',
        accent: '#fdda24',
        teal: '#00a7b5',
      },
      fontFamily: {
        headline: ['Lora', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '16px',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
